<?php

namespace AgendaBundle\Repository;
use UserBundle\Entity\User;
use AgendaBundle\Entity\Evenement;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByUser(User $user){
        $res = array();

        $res = array_merge($res, $user->getInterventions()->getValues());
        $res = array_merge($res, $user->getObservations()->getValues());

        foreach ($user->getAdjonctions() as $etab) {
            $res = array_merge($res, $etab->getEvenements()->getValues());
        }

        foreach ($user->getCorrespondances() as $etab) {
            $res = array_merge($res, $etab->getEvenements()->getValues());
        }

        $res = array_unique($res);

        return $res;
    }
}
