<?php

namespace AgendaBundle\Repository;

/**
 * type_interventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class type_interventionRepository extends \Doctrine\ORM\EntityRepository
{
}
