<?php

namespace AgendaBundle\Repository;

/**
 * type_lieuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class type_lieuRepository extends \Doctrine\ORM\EntityRepository
{
}
