agenda_homepage:
    path:     /
    defaults: {_controller: AgendaBundle:Evenement:index}

agenda_perso:
    path:     /perso
    defaults: { _controller: AgendaBundle:Agenda:agendaPerso }

admin_crud_lieux:
    resource: "@AgendaBundle/Resources/config/routing/evenement.yml"
    prefix:  /evenement

admin_search:
    path:     /search
    defaults: { _controller: AgendaBundle:Agenda:index }
