lieux_index:
    path:     /
    defaults: { _controller: "BackofficeBaseBundle:Lieux:index" }
    methods:  GET

lieux_show:
    path:     /{id}/show
    defaults: { _controller: "BackofficeBaseBundle:Lieux:show" }
    methods:  GET

lieux_new:
    path:     /new
    defaults: { _controller: "BackofficeBaseBundle:Lieux:new" }
    methods:  [GET, POST]

lieux_edit:
    path:     /{id}/edit
    defaults: { _controller: "BackofficeBaseBundle:Lieux:edit" }
    methods:  [GET, POST]

lieux_delete:
    path:     /{id}/delete
    defaults: { _controller: "BackofficeBaseBundle:Lieux:delete" }
    methods:  DELETE
