backoffice_base_homepage:
    path:     /
    defaults: { _controller: BackofficeBaseBundle:Default:index }

admin_crud_etablissement:
    resource: "@BackofficeBaseBundle/Resources/config/routing/etablissement.yml"
    prefix:   /etablissement

user_list:
    path: /user/list
    defaults: { _controller: BackofficeBaseBundle:UserAdmin:userList}

group_list:
    path: /group/list
    defaults: { _controller: BackofficeBaseBundle:GroupAdmin:groupList}
