backoffice_base_homepage:
    path:     /
    defaults: { _controller: BackofficeBaseBundle:Default:index }

admin_crud_lieux:
    resource: "@BackofficeBaseBundle/Resources/config/routing/lieux.yml"
    prefix:   /lieux

user_list:
    path: /user/list
    defaults: { _controller: BackofficeBaseBundle:UserAdmin:userList}

group_list:
    path: /group/list
    defaults: { _controller: BackofficeBaseBundle:GroupAdmin:groupList}
