backoffice_base_homepage:
    path:     /
    defaults: { _controller: BackofficeBaseBundle:Default:index }

admin_crud_etablissement:
    resource: "@BackofficeBaseBundle/Resources/config/routing/etablissement.yml"
    prefix:   /etablissement

admin_user:
    resource: "@BackofficeBaseBundle/Resources/config/routing/user.yml"
    prefix:   /user

group_list:
    path: /group/list
    defaults: { _controller: BackofficeBaseBundle:GroupAdmin:groupList}
